spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
#    url: jdbc:postgresql://localhost:5432/postgres3
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
logging:
  level:
    root: debug
    org.springframework: debug

